(#%require-dylib "libhelix_file_watcher" (only-in
    event-kind
    event-paths
    make-empty-watcher
    receive-event!
    receive-event-timeout!
    receive-paths!
    receive-paths-timeout!
    set-watched-files!
    unwatch-file!
    watch-controller
    watch-file!
    watch-file-list
    watch-recursive
))
(provide 
    event-kind
    event-paths
    make-empty-watcher
    receive-event!
    receive-event-timeout!
    receive-paths!
    receive-paths-timeout!
    set-watched-files!
    unwatch-file!
    watch-controller
    watch-file!
    watch-file-list
    watch-recursive
)
